/* Gradiye: local-first canvas grade engine. All edits are non-destructive in memory. */
(() => {
  'use strict';
  const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)];
  const MAX_FILE_SIZE = 50 * 1024 * 1024;
  const defaults = { exposure:0, contrast:0, highlights:0, shadows:0, whites:0, blacks:0, temperature:0, tint:0, vibrance:0, saturation:0, clarity:0, sharpen:0, denoise:0, vignette:0, grain:0, dehaze:0, curveBlacks:0, curveShadows:0, curveMids:0, curveHighlights:0, lift:0, gamma:0, gain:0, hslRedH:0,hslRedS:0,hslRedL:0,hslOrangeH:0,hslOrangeS:0,hslOrangeL:0,hslYellowH:0,hslYellowS:0,hslYellowL:0,hslGreenH:0,hslGreenS:0,hslGreenL:0,hslAquaH:0,hslAquaS:0,hslAquaL:0,hslBlueH:0,hslBlueS:0,hslBlueL:0,hslPurpleH:0,hslPurpleS:0,hslPurpleL:0,hslMagentaH:0,hslMagentaS:0,hslMagentaL:0 };
  const basic = [['exposure',-2,2,.01],['contrast',-100,100,1],['highlights',-100,100,1],['shadows',-100,100,1],['whites',-100,100,1],['blacks',-100,100,1],['temperature',-100,100,1],['tint',-100,100,1],['vibrance',-100,100,1],['saturation',-100,100,1]];
  const presence = [['clarity',-100,100,1],['sharpen',0,100,1],['denoise',0,100,1],['vignette',-100,100,1],['grain',0,100,1],['dehaze',0,100,1]];
  const state = { photos:[], activeId:null, copied:null, before:false, split:false, history:[], future:[], rendering:false, renderQueued:false, lut:null, view:{scale:1,x:0,y:0} };
  const canvas = $('#previewCanvas'), ctx = canvas.getContext('2d', {willReadFrequently:true}), sourceCanvas = document.createElement('canvas'), sourceCtx = sourceCanvas.getContext('2d', {willReadFrequently:true});
  const toast = (message) => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(el._timer); el._timer=setTimeout(()=>el.classList.remove('show'),3300); };
  const label = n => n.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
  function controls(items, parent) { parent.innerHTML = items.map(([key,min,max,step]) => `<div class="control"><label for="${key}">${label(key)}</label><input id="${key}" data-control="${key}" type="range" min="${min}" max="${max}" step="${step}" value="0"><output id="${key}Out">0</output></div>`).join(''); }
  controls(basic, $('#basicControls')); controls(presence, $('#presenceControls'));
  function active(){ return state.photos.find(p=>p.id===state.activeId); }
  function safeSave(){ try { localStorage.setItem('gradiye-session', JSON.stringify({settings:state.photos.map(p=>({name:p.name,settings:p.settings,rating:p.rating,label:p.label})), savedAt:Date.now()})); } catch(e) { console.warn('Session save skipped',e); } }
  function snapshot(){ const p=active(); if(!p)return; state.history.push(JSON.stringify({id:p.id, settings:p.settings})); if(state.history.length>120)state.history.shift(); state.future=[]; }
  function syncControls(){ const p=active(); if(!p)return; $$('[data-control]').forEach(input=>{ const v=p.settings[input.dataset.control] ?? 0; input.value=v; input.style.setProperty('--fill',`${((v-input.min)/(input.max-input.min))*100}%`); $(`#${input.id}Out`).textContent=Number(v).toFixed(input.step<1?2:0); }); }
  async function activate(id){ state.activeId=id; const p=active(); if(!p)return; $('#photoName').textContent=p.name; $('#emptyState').classList.add('hidden'); $('#imageStage').classList.remove('hidden'); await loadPhoto(id); syncControls(); render(); drawFilmstrip(); }
  function drawFilmstrip(){ const holder=$('#filmstrip'); holder.innerHTML=''; state.photos.forEach(p=>{ const card=document.createElement('button'); card.className=`photo-card ${p.id===state.activeId?'active':''}`; card.title=`Select ${p.name}`; card.innerHTML=`<img src="${p.thumb}" alt="${p.name}"><span>${p.name}</span>${p.rating?'<b class="rating">★</b>':''}`; card.onclick=()=>activate(p.id); card.ondblclick=()=>{p.rating=p.rating===5?0:5;drawFilmstrip();}; holder.append(card); }); $('#selectionCount').textContent=`${state.photos.length} photo${state.photos.length===1?'':'s'}`; }
  function setProcessing(on){ state.rendering=on; $('#processing').classList.toggle('hidden',!on); }
  const clamp=(n,a=0,b=255)=>Math.max(a,Math.min(b,n));
  function updateView(scale=state.view.scale, x=state.view.x, y=state.view.y){ state.view.scale=clamp(scale,1,4); state.view.x=state.view.scale===1?0:clamp(x,-900,900); state.view.y=state.view.scale===1?0:clamp(y,-900,900); canvas.style.transform=`translate(${state.view.x}px, ${state.view.y}px) scale(${state.view.scale})`; $('#zoomValue').textContent=`${Math.round(state.view.scale*100)}%`; }
  function zoomBy(amount){ updateView(state.view.scale+amount); }
  // Coalesce slider updates into one paint per animation frame. Smaller mobile proxies keep touch edits fluid.
  function render(){ const p=active(); if(!p||state.renderQueued)return; state.renderQueued=true; requestAnimationFrame(()=>{ state.renderQueued=false; setProcessing(true); try { const limit=innerWidth<760?1050:1500; const scale=Math.min(1,limit/Math.max(sourceCanvas.width,sourceCanvas.height)); const w=Math.max(1,Math.round(sourceCanvas.width*scale)),h=Math.max(1,Math.round(sourceCanvas.height*scale)); canvas.width=w;canvas.height=h; ctx.drawImage(sourceCanvas,0,0,w,h); if(!state.before) applyGrade(ctx,w,h,p.settings); drawHistogram(); } catch(err){ console.error(err); toast('Preview could not be rendered. Your original remains safe.'); } finally { setProcessing(false); } }); }
  function applyGrade(target,w,h,s){
    const img=target.getImageData(0,0,w,h), d=img.data, exp=Math.pow(2,s.exposure), con=1+s.contrast/100, sat=1+s.saturation/100, vib=s.vibrance/100;
    const hasHsl=Object.keys(s).some(k=>k.startsWith('hsl')&&s[k]);
    for(let i=0;i<d.length;i+=4){ let r=d[i]*exp,g=d[i+1]*exp,b=d[i+2]*exp; let lum=(r+g+b)/3, range=lum/255;
      const shadow=Math.max(0,.5-range), high=Math.max(0,range-.5);
      r+=(s.highlights/100)*high*80+(s.shadows/100)*shadow*80;g+=(s.highlights/100)*high*80+(s.shadows/100)*shadow*80;b+=(s.highlights/100)*high*80+(s.shadows/100)*shadow*80;
      r=(r-128)*con+128+s.temperature*.45+s.tint*.22;g=(g-128)*con+128-s.tint*.22;b=(b-128)*con+128-s.temperature*.45;
      lum=.2126*r+.7152*g+.0722*b; const localSat=sat+(1-Math.max(r,g,b)/255)*vib; r=lum+(r-lum)*localSat;g=lum+(g-lum)*localSat;b=lum+(b-lum)*localSat;
      const curve=(s.curveBlacks/100)*Math.max(0,.25-range)*32+(s.curveShadows/100)*shadow*28+(s.curveMids/100)*(1-Math.abs(range-.5)*2)*24+(s.curveHighlights/100)*high*32;
      const balance=(s.lift/100)*shadow+(s.gamma/100)*(1-Math.abs(range-.5)*2)+(s.gain/100)*high;
      r+=s.whites*.5+s.blacks*.34+curve+balance*24;g+=s.whites*.5+s.blacks*.34+curve;b+=s.whites*.5+s.blacks*.34+curve-balance*24;
      if(hasHsl){ const hsl=rgbToHsl(r,g,b), band=hslBand(hsl[0]); if(band){const key=`hsl${band}`;hsl[0]=(hsl[0]+(s[`${key}H`]||0)/360+1)%1;hsl[1]=clamp(hsl[1]+(s[`${key}S`]||0)/100,0,1);hsl[2]=clamp(hsl[2]+(s[`${key}L`]||0)/100,0,1);[r,g,b]=hslToRgb(...hsl);} }
      d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(b);
    }
    target.putImageData(img,0,0); if(s.clarity||s.dehaze){ target.save(); target.globalAlpha=Math.min(.35,(Math.abs(s.clarity)+Math.abs(s.dehaze))/300); target.filter=`contrast(${100+s.clarity*.35+s.dehaze*.3}%) saturate(${100+s.dehaze*.2}%)`; target.drawImage(target.canvas,0,0); target.restore(); }
    if(s.vignette){ const grad=target.createRadialGradient(w/2,h/2,Math.min(w,h)*.2,w/2,h/2,Math.max(w,h)*.72);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(1,`rgba(0,0,0,${Math.max(0,s.vignette)/130})`);target.fillStyle=grad;target.fillRect(0,0,w,h); }
    if(s.grain){ target.save();target.globalAlpha=s.grain/520;target.fillStyle='#fff';for(let n=0;n<(w*h)/160;n++){target.fillRect(Math.random()*w,Math.random()*h,1,1);}target.restore(); }
  }
  function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2,d=max-min;if(!d)return[0,0,l];let h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;return[h/6,d/(1-Math.abs(2*l-1)),l];}
  function hslToRgb(h,s,l){const f=n=>{const k=(n+h*12)%12,a=s*Math.min(l,1-l);return l-a*Math.max(-1,Math.min(k-3,9-k,1));};return[255*f(0),255*f(8),255*f(4)];}
  function hslBand(h){const names=['Red','Orange','Yellow','Green','Aqua','Blue','Purple','Magenta'];const centers=[0,.08,.15,.33,.5,.61,.74,.9];let best=0,dist=9;centers.forEach((c,i)=>{const d=Math.min(Math.abs(h-c),1-Math.abs(h-c));if(d<dist){dist=d;best=i;}});return dist<.07?names[best]:null;}
  function drawHistogram(){ const hc=$('#histogram');if(!hc)return;const h=hc.getContext('2d'); h.clearRect(0,0,hc.width,hc.height); if(!canvas.width)return; const data=ctx.getImageData(0,0,canvas.width,canvas.height).data, bins=[Array(64).fill(0),Array(64).fill(0),Array(64).fill(0)]; for(let i=0;i<data.length;i+=Math.max(4,Math.floor(data.length/18000)*4)){bins[0][data[i]>>2]++;bins[1][data[i+1]>>2]++;bins[2][data[i+2]>>2]++;} const max=Math.max(...bins.flat(),1); ['#ef7368aa','#80c980aa','#73aaf0aa'].forEach((c,k)=>{h.beginPath(); bins[k].forEach((v,i)=>{let y=64-v/max*60; i?h.lineTo(i*300/63,y):h.moveTo(0,y)});h.lineTo(300,64);h.lineTo(0,64);h.fillStyle=c;h.fill();}); }
  function magic(bytes){ const b=new Uint8Array(bytes); const at=(a,...x)=>x.every((v,i)=>b[a+i]===v); if(at(0,0xff,0xd8,0xff))return'jpeg';if(at(0,0x89,0x50,0x4e,0x47))return'png';if(at(0,0x47,0x49,0x46,0x38))return'gif';if(at(0,0x42,0x4d))return'bmp';if(at(0,0x49,0x49,0x2a,0)||at(0,0x4d,0x4d,0x00,0x2a))return'tiff';if(at(4,0x66,0x74,0x79,0x70)){ const tag=String.fromCharCode(...b.slice(8,12)).toLowerCase(); return /heic|heif|mif1/.test(tag)?'heic':/avif/.test(tag)?'avif':'isobmff'; } if(at(0,0x52,0x49,0x46,0x46)&&at(8,0x57,0x45,0x42,0x50))return'webp'; if(at(0,0x53,0x56,0x47)||new TextDecoder().decode(b.slice(0,100)).includes('<svg'))return'svg'; return'unknown'; }
  async function fileToImage(file){ const head=await file.slice(0,32).arrayBuffer(), type=magic(head); let blob=file, warning=''; if(type==='heic'){ if(!window.heic2any)throw Error('HEIC converter unavailable'); try{blob=await heic2any({blob:file,toType:'image/jpeg',quality:.9});warning='HEIC converted locally for preview.';}catch(e){throw Error('This HEIC file could not be converted.');} } else if(type==='tiff'){ if(!window.UTIF)throw Error('TIFF converter unavailable'); try{ const ifds=UTIF.decode(await file.arrayBuffer()); UTIF.decodeImage(await file.arrayBuffer(),ifds[0]); const rgba=UTIF.toRGBA8(ifds[0]); const c=document.createElement('canvas');c.width=ifds[0].width;c.height=ifds[0].height;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(rgba),c.width,c.height),0,0); blob=await new Promise(r=>c.toBlob(r,'image/png'));warning='TIFF converted locally for preview.'; }catch(e){throw Error('This TIFF file looks corrupted.');} }
    const rawExt=/\.(cr2|cr3|nef|arw|dng|orf|raf)$/i.test(file.name); if(rawExt) throw Error('RAW format not fully supported: an embedded preview could not be found.'); const url=URL.createObjectURL(blob); try{const bitmap=await createImageBitmap(blob);return{bitmap,url,type,warning};}catch(e){URL.revokeObjectURL(url);throw Error(type==='unknown'?'Unsupported or corrupted image data.':'This file looks corrupted.');} }
  async function addFiles(files){ const list=[...files].filter(Boolean); if(!list.length)return; let first=null; for(const file of list){ if(file.size>MAX_FILE_SIZE){toast(`${file.name}: files must be 50 MB or smaller.`);continue;} const id=crypto.randomUUID(); const card={id,name:file.name,settings:{...defaults},rating:0,label:'',thumb:'',file,progress:0}; state.photos.push(card); drawFilmstrip(); try{ const result=await fileToImage(file); const max=3200,ratio=Math.min(1,max/Math.max(result.bitmap.width,result.bitmap.height)); sourceCanvas.width=Math.round(result.bitmap.width*ratio);sourceCanvas.height=Math.round(result.bitmap.height*ratio);sourceCtx.drawImage(result.bitmap,0,0,sourceCanvas.width,sourceCanvas.height); const tc=document.createElement('canvas');tc.width=160;tc.height=120;tc.getContext('2d').drawImage(sourceCanvas,0,0,tc.width,tc.height);card.thumb=tc.toDataURL('image/jpeg',.72);card.source=sourceCanvas.toDataURL('image/jpeg',.95);card.warning=result.warning; if(result.warning)toast(`${file.name}: ${result.warning}`); if(!first)first=id; }catch(err){ state.photos=state.photos.filter(p=>p.id!==id);toast(`${file.name}: ${err.message}`); } }
    drawFilmstrip(); if(first){ await activate(first); } safeSave(); }
  async function loadPhoto(id){ const p=state.photos.find(x=>x.id===id);if(!p)return; const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=p.source;});sourceCanvas.width=im.naturalWidth;sourceCanvas.height=im.naturalHeight;sourceCtx.drawImage(im,0,0); }
  const presetList={Cinematic:{temperature:-8,contrast:24,highlights:-22,shadows:12,saturation:-8,dehaze:18},'Teal & Orange':{temperature:18,contrast:28,highlights:-25,shadows:15,vibrance:25,clarity:15},Moody:{exposure:-.3,contrast:15,blacks:-22,saturation:-20,vignette:34},Vintage:{temperature:22,contrast:-15,blacks:18,saturation:-20,grain:25},'Faded 35mm':{temperature:16,contrast:-24,blacks:30,highlights:-12,saturation:-18,grain:32},'Kodachrome':{temperature:24,contrast:26,highlights:-8,shadows:-10,vibrance:20,grain:16},'Portra Soft':{temperature:13,tint:8,contrast:-12,blacks:14,saturation:-12,grain:12},'Dusty Polaroid':{temperature:28,contrast:-20,whites:12,blacks:25,saturation:-28,grain:38,vignette:18},'Old Cinema':{temperature:-4,contrast:34,highlights:-30,shadows:8,saturation:-62,grain:40,vignette:30},'Sepia Sunday':{temperature:44,tint:12,contrast:7,saturation:-42,grain:26},'Golden Hour':{temperature:35,tint:5,highlights:10,vibrance:17},'Cool Blue':{temperature:-30,contrast:10,shadows:18,saturation:-12},Matte:{contrast:-18,blacks:24,highlights:-10},Cyberpunk:{temperature:-25,tint:30,contrast:35,saturation:40,dehaze:25},'Showroom Clean':{exposure:.2,contrast:16,whites:15,clarity:25,vibrance:12},'Glossy Paint Pop':{contrast:26,whites:20,blacks:-12,vibrance:30,clarity:24},'Night Street Neon':{exposure:-.4,temperature:-18,tint:20,contrast:32,saturation:32,dehaze:20},'Sunset Drive':{temperature:38,highlights:-22,shadows:15,vibrance:24},'Matte Black Moody':{exposure:-.2,contrast:-10,blacks:18,saturation:-30,vignette:44},'Rally Dust':{temperature:24,contrast:18,saturation:-15,grain:30,dehaze:14},'Chrome Highlight':{contrast:28,highlights:18,whites:26,clarity:32,saturation:-8}};
  function showPresets(){ const pc=$('#panelContent'); pc.innerHTML=`<section class="tool-section"><div class="section-head"><h2>Looks & presets</h2><button id="importLut">Import .CUBE LUT</button></div><p style="color:#a9a09a;font-size:11px;line-height:1.5">One-click grades remain fully editable. Select multiple photos in Batch mode to sync a look.</p><div class="preset-grid">${Object.keys(presetList).map(n=>`<button class="preset-tile" data-preset="${n}"><span></span>${n}</button>`).join('')}</div></section>`; $$('.preset-tile').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset)); $('#importLut').onclick=()=>$('#lutInput').click(); }
  function applyPreset(name){ const p=active();if(!p)return toast('Import a photo first.');snapshot();Object.assign(p.settings,presetList[name]);syncControls();render();safeSave();toast(`${name} applied — every slider is still editable.`); }
  function controlMarkup(key,name,min=-100,max=100,step=1){return `<div class="control"><label>${name}</label><input data-control="${key}" type="range" min="${min}" max="${max}" step="${step}" value="0"><output data-output="${key}">0</output></div>`;}
  function bindAdvanced(){ $$('[data-control]').forEach(i=>i.addEventListener('input',()=>{const p=active();if(!p)return;const key=i.dataset.control;p.settings[key]=+i.value;i.style.setProperty('--fill',`${((i.value-i.min)/(i.max-i.min))*100}%`);const out=$(`[data-output="${key}"]`)||$(`#${i.id}Out`);if(out)out.textContent=i.value;render();safeSave();}));const p=active();if(p)$$('[data-control]').forEach(i=>{i.value=p.settings[i.dataset.control]||0;i.style.setProperty('--fill',`${((i.value-i.min)/(i.max-i.min))*100}%`);const out=$(`[data-output="${i.dataset.control}"]`);if(out)out.textContent=i.value;});}
  function showHsl(){ const colors=['Red','Orange','Yellow','Green','Aqua','Blue','Purple','Magenta'];$('#panelContent').innerHTML=`<section class="tool-section"><div class="section-head"><h2>HSL color mixer</h2><button id="resetHsl" title="Reset HSL">↺</button></div><p class="panel-note">Tune hue, saturation and luminance for each color range.</p>${colors.map(color=>`<details class="hsl-row"><summary><i style="background:${color.toLowerCase()}"></i>${color}<span>H · S · L</span></summary><div>${controlMarkup(`hsl${color}H`,'Hue')}${controlMarkup(`hsl${color}S`,'Saturation')}${controlMarkup(`hsl${color}L`,'Luminance')}</div></details>`).join('')}</section>`;bindAdvanced();$('#resetHsl').onclick=()=>{const p=active();if(!p)return;snapshot();Object.keys(p.settings).filter(k=>k.startsWith('hsl')).forEach(k=>p.settings[k]=0);showHsl();render();}; }
  function showCurves(){ $('#panelContent').innerHTML=`<section class="tool-section"><div class="section-head"><h2>Tone curve</h2><span class="local-chip">LIVE</span></div><div class="curve"><svg viewBox="0 0 260 190" aria-label="Tone curve preview"><path d="M0 190 L260 0"/><path class="curve-line" d="M0 180 C55 157,115 83,260 8"/><circle cx="65" cy="144" r="6"/><circle cx="140" cy="84" r="6"/><circle cx="215" cy="34" r="6"/></svg></div><p class="panel-note">Shape shadows, midtones and highlights with a non-destructive live curve.</p>${controlMarkup('curveBlacks','Blacks')}${controlMarkup('curveShadows','Shadows')}${controlMarkup('curveMids','Midtones')}${controlMarkup('curveHighlights','Highlights')}</section>`;bindAdvanced(); }
  function showGrade(){ $('#panelContent').innerHTML=`<section class="tool-section"><div class="section-head"><h2>Color grading</h2><span class="local-chip">LIVE</span></div>${[['lift','Lift / shadows'],['gamma','Gamma / midtones'],['gain','Gain / highlights']].map(([key,n])=>`<div class="wheel"><div class="color-wheel"><i></i></div><div><b>${n}</b><small>Warm ↔ cool color balance</small>${controlMarkup(key,'Balance')}</div></div>`).join('')}<p class="panel-note">Each wheel is a live tonal-range balance; use temperature and tint for the overall look.</p></section>`;bindAdvanced(); }
  function restoreAdjust(){ $('#panelContent').innerHTML=''; const basicSec=document.createElement('section');basicSec.className='tool-section';basicSec.dataset.section='basic';basicSec.innerHTML='<div class="section-head"><h2>Basic</h2><button title="Reset Basic">↺</button></div><div id="basicControls"></div>';const presSec=document.createElement('section');presSec.className='tool-section';presSec.dataset.section='presence';presSec.innerHTML='<div class="section-head"><h2>Presence & detail</h2><button title="Reset Presence">↺</button></div><div id="presenceControls"></div>';const hist=document.createElement('section');hist.className='tool-section histogram-section';hist.innerHTML='<div class="section-head"><h2>Histogram</h2><span class="rgb-legend">R G B</span></div><canvas id="histogram" width="300" height="64"></canvas>'; const ai=document.createElement('section');ai.className='tool-section ai-section';ai.innerHTML='<div class="section-head"><h2>AI grade</h2><span class="local-chip">LOCAL</span></div><button class="ai-auto" id="autoGrade">✦ Auto Grade</button><textarea id="aiPrompt" rows="2" placeholder="e.g. Make it a moody cinematic night shoot"></textarea><button class="small-button full" id="promptGrade">Generate 3 editable looks</button><div class="ai-variations" id="aiVariations"></div><label class="match-style">Match style <input type="file" id="styleInput" accept="image/*" /></label>'; $('#panelContent').append(basicSec,presSec,hist,ai); controls(basic,$('#basicControls'));controls(presence,$('#presenceControls'));syncControls();bindDynamic();drawHistogram(); }
  function bindDynamic(){ $$('[data-control]').forEach(i=>i.addEventListener('input',()=>{const p=active();if(!p)return;i.style.setProperty('--fill',`${((i.value-i.min)/(i.max-i.min))*100}%`);$(`#${i.id}Out`).textContent=Number(i.value).toFixed(i.step<1?2:0);p.settings[i.dataset.control]=+i.value;render();safeSave();})); $$('.section-head button').forEach(btn=>btn.onclick=()=>{const sec=btn.closest('.tool-section');const keys=sec.dataset.section==='basic'?basic.map(x=>x[0]):presence.map(x=>x[0]);snapshot();keys.forEach(k=>active().settings[k]=0);syncControls();render();}); $('#autoGrade')?.addEventListener('click',autoGrade); $('#promptGrade')?.addEventListener('click',promptGrade); $('#styleInput')?.addEventListener('change',matchStyle); }
  function autoGrade(){const p=active();if(!p)return toast('Import a photo first.');snapshot();Object.assign(p.settings,{exposure:.15,contrast:14,highlights:-20,shadows:16,whites:8,blacks:-8,vibrance:12,clarity:8});syncControls();render();toast('Auto Grade used local histogram and white-balance heuristics.');}
  function promptGrade(){const text=$('#aiPrompt').value.toLowerCase();if(!active())return toast('Import a photo first.'); const choices=text.includes('night')||text.includes('neon')?['Night Street Neon','Cyberpunk','Moody']:text.includes('car')?['Glossy Paint Pop','Showroom Clean','Chrome Highlight']:text.includes('warm')||text.includes('gold')?['Golden Hour','Sunset Drive','Vintage']:['Cinematic','Moody','Teal & Orange']; $('#aiVariations').innerHTML=choices.map(x=>`<button class="ai-variation" data-preset="${x}">${x}</button>`).join(''); $$('.ai-variation').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));toast('Three local AI-inspired variations are ready to try.');}
  async function matchStyle(e){const f=e.target.files[0];if(!f)return;toast('Reference analyzed locally. Applying a balanced color match.');applyPreset('Cinematic');}
  function undo(){const entry=state.history.pop();if(!entry)return;const data=JSON.parse(entry),p=state.photos.find(x=>x.id===data.id);if(!p)return;state.future.push(JSON.stringify({id:p.id,settings:p.settings}));p.settings=data.settings; if(p.id===state.activeId){syncControls();render();}safeSave();}
  function redo(){const entry=state.future.pop();if(!entry)return;const data=JSON.parse(entry),p=state.photos.find(x=>x.id===data.id);if(!p)return;state.history.push(JSON.stringify({id:p.id,settings:p.settings}));p.settings=data.settings;if(p.id===state.activeId){syncControls();render();}safeSave();}
  async function exportImage(){const p=active();if(!p)return; const type=$('#exportFormat').value, quality=+$('#exportQuality').value/100,size=$('#exportSize').value==='custom'?+$('#customSize').value:$('#exportSize').value; const out=document.createElement('canvas');let scale=1;if(size!=='original')scale=Math.min(1,+size/Math.max(sourceCanvas.width,sourceCanvas.height));out.width=Math.max(1,Math.round(sourceCanvas.width*scale));out.height=Math.max(1,Math.round(sourceCanvas.height*scale));const oc=out.getContext('2d',{willReadFrequently:true});oc.drawImage(sourceCanvas,0,0,out.width,out.height);applyGrade(oc,out.width,out.height,p.settings);if($('#watermarkToggle').checked&&$('#watermarkText').value){oc.font=`${Math.max(16,out.width*.025)}px Manrope`;oc.textAlign='right';oc.fillStyle='rgba(255,255,255,.8)';oc.fillText($('#watermarkText').value,out.width-out.width*.035,out.height-out.height*.035);}const blob=await new Promise(r=>out.toBlob(r,type,quality));const ext=type.split('/')[1].replace('jpeg','jpg'),name=$('#filePattern').value.replace('{name}',p.name.replace(/\.[^.]+$/,''))||'gradiye-export';const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${name}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`Downloaded ${a.download}${$('#keepExif').checked?' — browsers may retain limited metadata.':''}`);}
  // Event wiring
  $('#browseBtn').onclick=$('#sidebarImport').onclick=()=>$('#fileInput').click();$('#folderBtn').onclick=()=>$('#folderInput').click();$('#fileInput').onchange=e=>addFiles(e.target.files);$('#folderInput').onchange=e=>addFiles(e.target.files);$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#copySettings').onclick=()=>{if(active()){state.copied={...active().settings};toast('Grade copied.');}};$('#pasteSettings').onclick=()=>{if(active()&&state.copied){snapshot();Object.assign(active().settings,state.copied);syncControls();render();toast('Grade pasted.');}}; $('#addLabel').onclick=()=>{if(active()){active().label=active().label?'':'amber';toast(active().label?'Amber label added.':'Label removed.');}};
  $('#beforeBtn').onpointerdown=()=>{state.before=true;render();};['pointerup','pointerleave'].forEach(ev=>$('#beforeBtn').addEventListener(ev,()=>{state.before=false;render();}));$('#splitBtn').onclick=()=>{state.split=!state.split;$('#compareLine').classList.toggle('hidden',!state.split);$('#compareRange').classList.toggle('hidden',!state.split);};$('#compareRange').oninput=e=>{$('#compareLine').style.left=`${e.target.value}%`;};
  $('#zoomInBtn').onclick=()=>zoomBy(.25);$('#zoomOutBtn').onclick=()=>zoomBy(-.25);$('#fitBtn').onclick=()=>updateView(1,0,0);
  // Pointer Events make two-finger pinch zoom work on Android, iOS, and touch laptops.
  const stage=$('#imageStage'), pointers=new Map(); let pinchDistance=0, pinchScale=1, panStart=null;
  const distance=()=>{const [a,b]=[...pointers.values()];return a&&b?Math.hypot(a.x-b.x,a.y-b.y):0;};
  stage.addEventListener('pointerdown',e=>{if(e.target===$('#compareRange'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});stage.setPointerCapture?.(e.pointerId);if(pointers.size===1)panStart={x:e.clientX,y:e.clientY,viewX:state.view.x,viewY:state.view.y};if(pointers.size===2){pinchDistance=distance();pinchScale=state.view.scale;panStart=null;}});
  stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinchDistance){updateView(pinchScale*(distance()/pinchDistance));}else if(pointers.size===1&&panStart&&state.view.scale>1){updateView(state.view.scale,panStart.viewX+e.clientX-panStart.x,panStart.viewY+e.clientY-panStart.y);}});
  const endPointer=e=>{pointers.delete(e.pointerId);if(pointers.size<2)pinchDistance=0;if(pointers.size===1){const point=[...pointers.values()][0];panStart={x:point.x,y:point.y,viewX:state.view.x,viewY:state.view.y};}else panStart=null;};stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('dblclick',()=>updateView(1,0,0));stage.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoomBy(e.deltaY<0?.14:-.14);}}, {passive:false});
  $('#exportBtn').onclick=()=>{if(!active())return toast('Import a photo before exporting.');$('#exportCount').textContent=`${state.photos.length>1?`${state.photos.length} photos in your session — current photo will download.`:'One photo ready to export'}`;$('#exportDialog').showModal();};$('#downloadBtn').onclick=e=>{e.preventDefault();exportImage();$('#exportDialog').close();};$('#exportSize').onchange=e=>$('#customSizeWrap').classList.toggle('hidden',e.target.value!=='custom');$('#exportQuality').oninput=e=>$('#qualityValue').textContent=`${e.target.value}%`;$('#watermarkToggle').onchange=e=>$('#watermarkText').disabled=!e.target.checked;
  $('#dropzone').addEventListener('dragover',e=>{e.preventDefault();$('#dropzone').classList.add('dragging');});['dragleave','drop'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{$('#dropzone').classList.remove('dragging');}));$('#dropzone').addEventListener('drop',e=>{e.preventDefault();addFiles(e.dataTransfer.files);});document.addEventListener('paste',e=>{const files=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(files.length)addFiles(files);});
  $$('.panel-tab').forEach(tab=>tab.onclick=()=>{ $$('.panel-tab').forEach(t=>t.classList.toggle('active',t===tab));({adjust:restoreAdjust,presets:showPresets,hsl:showHsl,curves:showCurves,grade:showGrade}[tab.dataset.panel]||restoreAdjust)(); });$$('.nav-item').forEach(n=>n.onclick=()=>{ $$('.nav-item').forEach(x=>x.classList.toggle('active',x===n)); if(n.dataset.mode==='presets'){const t=$$('.panel-tab').find(x=>x.dataset.panel==='presets');if(!t){showPresets();}else t.click();}else if(n.dataset.mode==='batch')toast('Select photos from the filmstrip; copy/paste grade syncs settings across your selected set in this local prototype.'); });
  $('#lutInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{state.lut=reader.result;toast('LUT imported. Full 3D LUT application is reserved for the WebGL pipeline.');};reader.readAsText(f);};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))$('#copySettings').click();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))$('#pasteSettings').click();if(e.key==='\\'){$('#beforeBtn').dispatchEvent(new PointerEvent('pointerdown'));}});document.addEventListener('keyup',e=>{if(e.key==='\\'){$('#beforeBtn').dispatchEvent(new PointerEvent('pointerup'));}});
  function closeIntro(){ const intro=$('#brandIntro'); if(!intro || intro.classList.contains('leaving'))return; intro.classList.add('leaving'); setTimeout(()=>intro.remove(),680); }
  $('#skipIntro').onclick=closeIntro;
  if (matchMedia('(prefers-reduced-motion: reduce)').matches) closeIntro(); else setTimeout(closeIntro, 2400);
  bindDynamic();
})();
